treasure-data/perfectqueue

lib/perfectqueue.rb, lib/perfectqueue/multiprocess/child_process.rb, lib/perfectqueue/signal_thread.rb, lib/perfectqueue/supervisor.rb, lib/perfectqueue/worker.rb
I confirmed that the `PerfectQueue::SignalQueue` cannot handle signals on Ruby 2.1.x. I found that Ruby 2.0+ doesn't allow to call `Mutex#lock` in `trap`.
To deal with, I backported `ServerEngine::SignalThread` from serverengine v1.5.10.
// We need to apply similar fix to `perfectsched` as well
=> Backported `ServerEngine::SignalThread` from serverengine v1.5.10

.travis.yml, README.md, circle.yml, lib/perfectqueue/backend/rdb_compat.rb, perfectqueue.gemspec, spec/rdb_compat_backend_spec.rb, spec/spec_helper.rb
`LOCK TABLES` causes `Waiting for table metadata lock` contention issue.
It is better to use `GET_LOCK` instead of `LOCK TABLES` in MySQL.
=> Avoid table metadata lock in MySQL

lib/perfectqueue/multiprocess/thread_processor.rb
* In real application, its too huge to read, and also danger to dump all data for task in logs
=> Remove dump of task request:

lib/perfectqueue/backend/rdb_compat.rb
In the old days it uses `SELECT FOR UPDATE` and require transaction.
But these days it introduces `LOCK TABLES` and `GET_LOCK()` and don't
need transaction.
=> Remove useless transaction

lib/perfectqueue/backend/rdb_compat.rb
Manual says "The DO statement is convenient to use with RELEASE_LOCK()."
https://dev.mysql.com/doc/refman/5.6/en/miscellaneous-functions.html#function_release-lock
=> Use DO Syntax for RELEASE_LOCK()

lib/perfectqueue/backend/rdb_compat.rb, spec/rdb_compat_backend_spec.rb
* Separate the area where a DELETE query locks from the area where
acquire query touchs. By this change DELETE query and acquire query
can run parallel.
** finished task was SET timeout=now+retention_time, created_at=NULL.
This intoroduces DELETE_OFFSET=10_0000_0000, and change as
SET timeout=now-DELETE_OFFSET+retention_time, created_at=NULL.
** To separate tasks to be acquired from tasks to be deleted,
introduce EVENT_HORIZON(=13_0000_0000, 2011-03-13 07:06:40 UTC).
Now it doesn't check prior that.
NOTE: this change requires migration process like actual DELETE query
see WHERE timeout <= now AND created_at IS NULL.
=> Separate delete and acquire queries

lib/perfectqueue/backend/rdb_compat.rb, spec/rdb_compat_backend_spec.rb
On migrating, workers may be stolen some of tasks by another workers.
To ease such migrating, detect the situation and release those tasks.
Tasks other than already acquired ones will be acquired after tiemout.
=> Check timeout on UPDATE in acquire

spec/rdb_stress.rb
Also note that with master, it works fine with 6M waiting tasks.
With v0.8.45:
PerfectQueue::Backend::RDBCompatBackend
#acquire
some tasks
D, [2016-03-07T17:30:47.700983 #35536] DEBUG -- : (0.000104s) SET @@wait_timeout = 2147483
D, [2016-03-07T17:30:47.701119 #35536] DEBUG -- : (0.000062s) SET SQL_AUTO_IS_NULL=0
D, [2016-03-07T17:30:47.701310 #35536] DEBUG -- : (0.000066s) BEGIN
D, [2016-03-07T17:30:47.701497 #35536] DEBUG -- : (0.000116s) SELECT GET_LOCK('test_queues', 60) locked
D, [2016-03-07T17:30:49.155729 #35536] DEBUG -- : (1.454003s) DELETE FROM `test_queues` WHERE timeout <= 1457339447 AND created_at IS NULL
D, [2016-03-07T17:30:49.157869 #35536] DEBUG -- : (0.002047s) COMMIT
D, [2016-03-07T17:30:49.158730 #35536] DEBUG -- : (0.000071s) SET @@wait_timeout = 2147483
D, …
=> Add a stress test for long waiting queue

lib/perfectqueue/backend/rdb_compat.rb
Commit a7dfe18146263ecd01541970041732a09fad39ed adds a condition with timeout
to UPDATE query of acuring tasks.
It also introduced a change for MySQL wrongly to use timeout as index.
With FORCE INDEX(PRIMARY) MySQL correctly use PRIMARY KEY as index.
Also note that index hints for UPDATE query is MySQL 5.5.6 or later http://dev.mysql.com/doc/refman/5.5/en/update.html
=> Add FORCE INDEX(PRIMARY) to UPDATE query not to use timeout as index

lib/perfectqueue/backend/rdb_compat.rb
If @cleanup_interval is large and starts all workers same time,
cleanup runs periodically in large interval.
=> Randomize initial @cleanup_interval_count

lib/perfectqueue/backend/rdb_compat.rb
To avoid deadlock between 44's and 48's delete query.
=> Run 48's delete query in connect_locked

lib/perfectqueue/backend/rdb_compat.rb
It doesn't need to check created_at.
=> v0.8.48's timeout express taks's life

lib/perfectqueue/backend/rdb.rb
https://github.com/treasure-data/perfectqueue/blob/v0.8.48/lib/perfectqueue/backend/rdb_compat.rb#L24-L34
=> Support v0.8.48's timeout model

spec/rdb_compat_backend_spec.rb
db.acquire calls `Time.now` in it.
If it is different from `let (:now){ Time.now.to_i }`, the spec will fail.
=> fix random failure

ChangeLog, lib/perfectqueue/backend/rdb_compat.rb, spec/rdb_compat_backend_spec.rb
To acquire tasks, run UPDATE and SELECT instead of SELECT and UPDATE.
This adds a new column `owner` to identify which connection acquires the task.
With this column, `RDBCompatBackend#acquire` now doesn't get table lock nor use
`GET_LOCK()`, but adopt mark-and-select method.
It locks only oldest N rows and their gaps during UPDATE.
CONNECTION_ID()
---------------
64bit unsigned integer from the server's internal thread ID counter.
This is unique while the MySQL server running.
http://dev.mysql.com/doc/refman/5.6/en/information-functions.html#function_connection-id
https://bugs.mysql.com/bug.php?id=19806
References
---------------
* http://yuuki.hatenablog.com/entry/go-and-mysql-jobqueue
* https://blog.engineyard.com/2011/5-subtle-ways-youre-using-mysql-as-a-queue-and-why-itll-bite-you …
=> UPDATE first strategy for finer grained locking

README.md, lib/perfectqueue/backend/rdb_compat.rb, lib/perfectqueue/client.rb, lib/perfectqueue/command/perfectqueue.rb, lib/perfectqueue/task.rb, lib/perfectqueue/task_metadata.rb, lib/perfectqueue/task_monitor.rb, lib/perfectqueue/task_status.rb, spec/queue_spec.rb, spec/rdb_compat_backend_spec.rb, spec/task_monitor_spec.rb
cancel_request is not compatible with v0.7's cancel behavior,
and does not work because it doesn't delete canceled tasks.
=> Remove cancel_request

bin/stress, lib/perfectqueue/backend/rdb_compat.rb
* FOR UPDATE is not required in this version to avoid deadlock.
* call RELEASE_LOCK() earlier.
=> FOR UPDATE is not required while with GET_LOCK()

lib/perfectqueue/backend/rdb_compat.rb, spec/rdb_compat_backend_spec.rb
If resource limit is used, such queue doesn't need performance so much.
Therefore use old strategy at this time.
=> Use v08's strategy if resource limit is used

.travis.yml, circle.yml
CircleCI 1.0 is not working anymore, and I don't think it's worth running in addition to Travis.
Also I upgraded Ruby versions tested by Travis. I still kept Ruby 2.3 because somebody may be still using Ruby 2.3.
=> Maintain CI configurations

.travis.yml, circle.yml, lib/perfectqueue/backend/rdb_compat.rb
https://github.com/treasure-data/perfectqueue/pull/57 looks wanted to merge https://github.com/treasure-data/perfectqueue/pull/56 to v08 branch which is used by [td-worker](https://github.com/treasure-data/td-worker) but it wrongly merged into master.
This also includes https://github.com/treasure-data/perfectqueue/pull/63.
=> Add sleep lock retrying with exponential-backoff

lib/perfectqueue/backend/rdb.rb, lib/perfectqueue/backend/rdb_compat.rb, spec/rdb_backend_spec.rb, spec/rdb_compat_backend_spec.rb
This PR introduces new config parameter :max_retry_count to customize the threshold of connect error retry. In the current implementation, the retry count is hard-coded in backend/{rdb,rdb_compat}.rb. It should be extracted to make it customizable for each environment.
=> Extract max_retry_count as config parameter

lib/perfectqueue/backend/rdb.rb, perfectqueue.gemspec, spec/rdb_backend_spec.rb
We want to control `ssl_mode` option in some cases.
=> Support ssl_mode option for RDBBackend
